gpus: 2
batch_size: 4
image_size: [416, 416]
classes: 20
anchors: [[10, 13], [16, 30], [33, 23], [30, 61], [62, 45], [59, 119], [116, 90], [156, 198], [373, 326]]
masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
learning_rate: 0.001
l2_decay: 0.0001
model_dir: "./model_v2"
train_files:
  - "/home/sunjiahe/Datasets/VOCDataset/yolo_train.txt"
eval_files:
  - "/home/sunjiahe/Datasets/VOCDataset/yolo_test.txt"
test_files:
  - "/home/sunjiahe/Datasets/VOCDataset/2007_test.txt"
